export const galleryPhotos = [
  '12', '10', '15', '13', '05', '06', '07', '08', '09', '02', '01', '03', '04', '11', '14',
];

export const defaultSiteContent = {
  brandName: "Camila's Cerimonial",
  logoUrl: '',
  heroLead: 'Juntos transformando',
  heroAccent: 'sonhos em realidade',
  heroSubtitle: 'Assessoria e cerimonial dedicados a cuidar de cada detalhe do seu casamento, festa de 15 anos ou evento especial.',
  stats: [
    { value: '150+', label: 'Sonhos Realizados' },
    { value: '5.0', label: 'Avaliação dos Clientes', star: true },
    { value: '100%', label: 'Dedicação' },
  ],
  marqueeText: 'Cerimonial e Assessoria ● Planejamento Completo ● Cuidado em Cada Detalhe',
  galleryTag: 'Galeria de Eventos',
  galleryLead: 'Veja alguns',
  galleryAccent: 'momentos inesquecíveis',
  gallery: [
    { photo: '12', title: 'Casamentos Inesquecíveis' },
    { photo: '10', title: 'Momentos Mágicos' },
    { photo: '15', title: 'Festas de 15 Anos' },
    { photo: '13', title: 'Decoração & Sofisticação' },
    { photo: '05', title: 'Eventos Exclusivos' },
    { photo: '06', title: 'Cerimônias ao Ar Livre' },
    { photo: '07', title: 'Produção Completa' },
    { photo: '08', title: 'Atenção a Cada Detalhe' },
    { photo: '09', title: 'Sonhos Realizados' },
    { photo: '02', title: 'Equipe Especializada' },
  ],
  packagesTag: 'Propostas Comerciais',
  packagesLead: 'Conheça nossos',
  packagesAccent: 'Pacotes & Serviços',
  completeBadge: 'Mais Escolhida',
  completeButton: 'Solicitar Proposta Completa (PDF)',
  ceremonyButton: 'Solicitar Proposta Cerimonial (PDF)',
  contactButton: 'Solicitar Orçamento',
  calloutTitle: 'Faça seu Orçamento!',
  calloutText: 'E nos permita transformar seus sonhos em realidade.',
  calloutButton: 'Conversar',
  whatsappPhone: '31985165246',
  footerText: 'Todos os direitos reservados.',
  developerName: 'Gabriel.',
  developerUrl: 'https://www.instagram.com/eu.gabrielvieira/',
};
